### PR TITLE
Feat/upgrade babel preset

### PR DESCRIPTION
**Pull request by Crash--**

### CODE REVIEW

**Comment by paultranvan** [comment]
The CI seems unhappy, but nice work! :clap: 
Although, some PR description about the context would be nice ;)

**Review by paultranvan — APPROVED** [review]
A conflict to solve, but LGTM, thanks!

**Comment by Crash--** [comment]
Will work on it soon

**Review by Ldoppea — APPROVED** [review]

**Comment by trollepierre** [comment]
> Oops! Something went wrong! :(

> ESLint: 8.14.0

> Error: Failed to load parser 'babel-eslint' declared in 'packages/cozy-client/examples/web/package.json » eslint-config-react-app': Cannot find module 'babel-eslint'

D'après travis

**Pull request closed without merging**
