### PR TITLE
Fix AppCollection

### PR DESCRIPTION
**Pull request by gregorylegarec**
In #41 I added AppCollection but it was a little bit too soon, because it appeared later that it was not working as expected in Collect.

So there is a fix, before merging I wish to:

* [x] Add tests
* [x] throw errors when not implemented or not available methods like `find()`, `get()`, etc... are called.

### CODE REVIEW

**Comment by gregorylegarec** [comment]
@ptbrowne @y-lohse  Ready to be reviewed and to merge !

**Comment by ptbrowne** [comment]
lint please

**Comment by gregorylegarec** [comment]
@ptbrowne My bad the file was not saved on my machine. 👌

**Comment by CPatchane** [comment]
Thanks @gregorylegarec 💛

**Comment by y-lohse** [comment]
(Late to the party, but 👍 )

**Pull request merged**
