### PR TITLE
feat: Instanciating new CozyClient now add capabilities to it

### PR DESCRIPTION
**Pull request by JF-Cozy**
see commit messages

### CODE REVIEW

**Comment by Crash--** [comment]
+1 for the first commit, but I don't understand the second (I think we don't need those changes, how did you generate them ?)

**Comment by JF-Cozy** [comment]
> +1 for the first commit, but I don't understand the second (I think we don't need those changes, how did you generate them ?)

en faisant `yarn types` mais effectivement ça a l'air poser problème...

**Comment by ptbrowne** [comment]
Tes node_modules sont à jour ?

**Comment by JF-Cozy** [comment]
> Tes node_modules sont à jour ?

arf c'est bien probable que non !

**Review by Crash-- — APPROVED** [review]

**Pull request merged**
