### PR TITLE
feat: Add deleteFileId* functions

### PR DESCRIPTION
**Pull request by Merkur39**
Avoid the app to have to fetch the document if it has only its ID, to be able to delete it

### CODE REVIEW

**Review by Crash-- — CHANGES_REQUESTED** [review]
I'm not very happy to have it inside the model. We'll have to add these methods in every doctypes we use. This is not futur proof. 

Why not updating at least the `CozyClient.destroy()` method to also accept only `_type` and `_id`? And make the request to get the document before calling the rest of the method? 

Also, it seems that there is a `destroyAll()` in Document Collection. Maybe we should expose it from CozyClient

**Comment by Merkur39** [comment]
Indeed, I went a bit fast on my development
I had another logic in mind but it doesn't exist... :man-shrugging:

**Comment by Merkur39** [comment]
For `CozyClient.destroy`, I don't think it is really relevant.
For `CozyClient.destroyAll`, the `destroyAll` method of `DocumentCollection` uses its `updateAll` method, but the `io.cozy.files` are write locked.
https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/DocumentCollection.js#L391

The simplest approach would be to loop over `CozyClient.destroy` and not create a new mutation (?)

**Comment by Merkur39** [comment]
I propose to continue the discussion on this issue https://github.com/cozy/cozy-client/issues/1075

**Pull request closed without merging**
