### PR TITLE
feat: Add activity theme

### PR DESCRIPTION
**Pull request by Merkur39**
Added `activity` theme & `other_activity_document` label.
Moved `personal_sporting_licence` label from `identity` theme to `activity` theme

### CODE REVIEW

**Comment by Merkur39** [comment]
[Ajout d'un thème & label dans Cozy Client](https://trello.com/c/o3cqfjZ4/833-ajout-dun-th%C3%A8me-label-dans-cozy-client)

**Review by JF-Cozy — COMMENTED** [review]
le "Moved `personal_sporting_licence` label" n'est pas un BC ? 🤔

**Comment by Merkur39** [comment]
> le "Moved `personal_sporting_licence` label" n'est pas un BC ? 🤔

Je ne pense pas, @paultranvan saurais-tu confirmer ? 😇

**Comment by paultranvan** [comment]
If an app uses it, it would be a breaking change, but I guess this is not the case yet, right? If yes, I assume there is no need for a BC

**Comment by Merkur39** [comment]
> If an app uses it, it would be a breaking change, but I guess this is not the case yet, right? If yes, I assume there is no need for a BC

The change is very recent (3 weeks) here https://github.com/cozy/cozy-client/pull/1093/files
And I confirm that no app (Cozy) uses it

**Review by Crash-- — APPROVED** [review]

**Pull request merged**
